include("${CMAKE_CURRENT_LIST_DIR}/../target-profiles/stm32f407.cmake")

set(BOARD_MCU_NAME STM32F407IGH6)
set(BOARD_CPU_OPTIONS ${STM32F407_CPU_OPTIONS})
set(BOARD_LINKER_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/stm32f407ighx-flash.ld")
