FROM ubuntu:24.04

LABEL maintainer "montana <2398925789@qq.com>"

ARG ED_VERSION=2025Q1

ARG NICKNAME=noble

ARG MAIN_USER=vvpie

USER root
WORKDIR /root

# sources mirror
RUN echo "Types: deb" > /etc/apt/sources.list.d/ubuntu.sources && \
    echo "URIs: http://mirrors.tuna.tsinghua.edu.cn/ubuntu" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Suites: ${NICKNAME} ${NICKNAME}-updates ${NICKNAME}-backports" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Components: main restricted universe multiverse" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Types: deb" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "URIs: http://mirrors.tuna.tsinghua.edu.cn/ubuntu" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Suites: ${NICKNAME}-security" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Components: main restricted universe multiverse" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >> /etc/apt/sources.list.d/ubuntu.sources && \
    apt-get update -y && apt-get upgrade -y

# basic tools and locale setup
RUN apt-get install curl wget gnupg software-properties-common locales tzdata zsh -y && \
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && \
locale-gen && \
echo "LANG=en_US.UTF-8" >> /etc/locale.conf


# package install
RUN apt-get update
# essential tools
RUN apt-get install \
    dpkg-dev \
    make \
    cmake \
    git \
    rsync \
    tar \
    nano \
    vim \
    openssh-server \
    iputils-ping  \
    unzip  \
    binutils-dev \
    dmidecode \
    sudo \
    figlet \
    -y

# development tools
RUN apt-get install \
    g++-${GCC_VERSION} \
    gcc-${GCC_VERSION} \
    gdb \
    clangd-${LLVM_VERSION} \
    lldb-${LLVM_VERSION} \
    clang-${LLVM_VERSION} \
    lld-${LLVM_VERSION} \
    python3 \
    python3-pip \
    -y